# Profile information
name: Chae-Yeun Park 
title: Chae-Yeun Park
description: > # this means to ignore newlines until "baseurl:"
    Chae-Yeun Park's personal homepage and blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "chaeyeunpark.me" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github: chaeyeunpark
twitter: chae_yeun_park

# Contact form
email: chae.yeun.park@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
